jobs:
  include:
    - stage: Build project with sonarqube
      if: tag IS blank
      
      language: java
      git:
        depth: false

      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
    
      addons:
        sonarcloud:
          organization: "kabassu-github"
          branches:
            - .?
      script:
        - gradle sonarqube
        
    - stage: Prepare docker file 
      if: ((branch = master) AND (type IN (push)) OR tag IS present)
      sudo: required

      services:
        - docker

      script:
        - wget https://github.com/openshift/source-to-image/releases/download/v1.1.8/source-to-image-v1.1.8-e3140d01-linux-amd64.tar.gz -O /tmp/s2i.tar.gz ;
          tar -xvf /tmp/s2i.tar.gz ;
          ls $PWD ;
          export PATH=$PATH:$PWD ;
   
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD";
          docker pull kabassu/kabassu-s2i:latest;
          s2i build https://github.com/Kabassu/kabassu kabassu/kabassu-s2i:latest kabassu/kabassu;
          echo $TRAVIS_TAG;
          if [ -z "${TRAVIS_TAG}" ];
          then          
              docker push kabassu/kabassu;
          else
              docker tag kabassu/kabassu kabassu/kabassu:$TRAVIS_TAG;
              docker push kabassu/kabassu:$TRAVIS_TAG;  
          fi;
          
          
