openapi: 3.0.0
info:
  title: Kabassu API
  description: API for Kabassu system
  version: 0.0.1
paths:
  /kabassu/getrequest/{id}:
    get:
      operationId: getrequest
      summary: get test request by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
           type: string
          description: Test Request ID
      responses:
        '200':
          description: Retrieved object
  /kabassu/getdefinition/{id}:
    get:
      operationId: getdefinition
      summary: get test definition by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
           type: string
          description: Test Definition ID
      responses:
        '200':
          description: Retrieved object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestDefinition'
              examples: 
                Local_gradle:
                  value:
                    name: test
                    runner: gradle
                    locationType: filesystem
                    location: '../junit5-test'  
                    paths:
  /kabassu/getall/{collection}/{page}/{pagesize}:
    get:
      operationId: getall
      summary: get all data from collection
      parameters:
        - in: path
          name: collection
          required: true
          schema:
           type: string
          description: collection name
        - in: path
          name: page
          required: true
          schema:
           type: integer
          description: page
        - in: path
          name: pagesize
          required: true
          schema:
           type: integer
          description: page size
      responses:
        '200':
          description: ok
  /kabassu/getallbyfield/{collection}/{field}/{value}/{page}/{pagesize}:
    get:
      operationId: getallbyfield
      summary: get all data from collection by field
      parameters:
        - in: path
          name: collection
          required: true
          schema:
           type: string
          description: collection name
        - in: path
          name: field
          required: true
          schema:
           type: string
          description: field name
        - in: path
          name: value
          required: true
          schema:
           type: string
          description: value
        - in: path
          name: page
          required: true
          schema:
           type: integer
          description: page
        - in: path
          name: pagesize
          required: true
          schema:
           type: integer
          description: page size
      responses:
        '200':
          description: ok
  /kabassu/adddefinition:
    post:
      operationId: adddefinition
      summary: Adds a new test definition to be run with Kabassu
      requestBody:
        description: JSON File containing test definition data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestDefinition'
            examples:
              Local_gradle:
                value:
                  name: test
                  runner: gradle
                  locationType: filesystem
                  location: '../junit5-test'
              
      responses:
        '201':
          description: Added
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Test Definition Id
                    
  /kabassu/test/run:
    post:
      operationId: testrun
      summary: Run tests 
      requestBody:
        description: JSON File containing test run data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestRun'
      responses:
        '200':
          description: Test is running

  /kabassu/test/rerun:
    post:
      operationId: testrerun
      summary: ReRun tests 
      requestBody:
        description: JSON File containing test id
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestReRun'
      responses:
        '200':
          description: Test is running
          
components:
  schemas:
    TestDefinition:
        type: object
        properties:
          name:
            type: string
          runner:
            type: string
          runnerOptions:
            type: array
            items:
                type: string
          locationType:
            type: string
          location:
            type: string
          reports:
            type: array
            items:
                type: string
    TestRun:
      type: object
      properties: 
        definitionId: 
          type: string
        configurationId: 
          type: string
        jvm:
          type: string
        description:
          type: string
        additionalData: 
          type: object
    TestReRun:
      type: object
      properties: 
        requestId: 
          type: string
